config/routes.rb
Lalala::Application.routes.draw do

  root to: "static_pages#home"

  get "signout" => "sessions#destroy"
  get "signin" => "sessions#new"
  get "signup" => "users#new", :as => "signup"


  namespace :api do
    resources :posts, except: [:new, :edit]
    resources :users, except: [:new, :edit]
    resources :messages, except: [:edit, :update]
    resources :sessions, except: [:edit, :update, :new, :show]
  end


end

app/models/message.rb
class Message < ActiveRecord::Base

  is_private_message
  attr_accessible :recipient_id, :subject, :body, :read_at, :sender_id

  
end

app/controllers/api/messages_controller.rb
module Api
  class MessagesController < ApplicationController

    skip_before_filter :verify_authenticity_token
    before_filter :authenticate

    def index
      @messages = Message.all
      respond_to do |format|
        format.json
      end
    end

    def show
      @message = Message.where(id: params[:id]).first
      respond_to do |format|
        format.json {
          render json: { error_message: "Not found", status: 404 } and return unless @message
        }
      end
    end

    def create
      @message =  Message.create(params[:message])
      if @message.save
        render json: @message , status: 201
      else
        render json: @message.errors, status: 422
      end
    end

    def authenticate
      authenticate_token || render_unauthorized
    end

    def authenticate_token
      authenticate_with_http_token do |token, options|
        User.where(auth_token: token).first
      end
    end

    def render_unauthorized
      render json: "Bad credentials", status: 401
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController


  def index
    @messages = params[:sent] == "1" ? current_user.sent_messages : current_user.received_messages
  end

  def show
    @message = Message.read_message(params[:id], current_user)
    redirect_to root_url unless @message.present?
  end

  def new
    @message = Message.new
  end

  def create
    @message = current_user.sent_messages.create params[:message]
    redirect_to messages_path(:sent => 1)
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_received.html.erb
<h4>Received messages</h4>
<% if @messages.empty? %>
    You have not received any message
<% end %>
<% @messages.each do |m| %>
    <div class="row">
      <div class="large-10 columns">
        <%= link_to message_path(m) do %>
            <div class="message">
              <% unless m.message_read? %><div class="unread"></div><% end %>
              from: <%= content_tag( :span, m.sender.full_name, :class => "name") %><br>
              subject: <%= content_tag( :span, m.subject, :class => "subject") %>
              <br/> <br/>
              <%= content_tag( :p, m.body) %>
            </div>
        <% end %>
      </div>
    </div>
<% end %>

app/views/messages/_sent.html.erb
<h4>Sent messages</h4>
<% if @messages.empty? %>
    You have not sent a single message
<% end %>
<% @messages.each do |m| %>
    <div class="row">
      <div class="large-10 columns">
        <%= link_to message_path(m) do%>
            <div>
              <% unless m.message_read? %><div class="unread"></div><% end %>
              To: <%= content_tag( :span, m.recipient.full_name, :class => "name") %><br>
              Subject: <%= content_tag( :span, m.subject, :class => "subject") %>
              <br/> <br/>
              <%= content_tag( :p, m.body) %><hr style="border-color: #000000;">
            </div>
        <% end %>
      </div>
    </div>
<% end %>

app/views/messages/index.html.erb
<right></right><%= link_to "New message", new_message_path, class: "btn btn-large btn-primary ", style: "margin-left:5px; background: #000000;" %>
<div class="section-container auto" data-section>
  <section <% if params[:sent] !="1" %> class="active" <%end%> >
    <!--<p class="title" data-section-title><a href="#panel1">Received</a></p>-->
    <div class="content" data-section-content>
      <%= render "received" %>
    </div>
  </section>
  <section <% if params[:sent] == "1" %> class="active" <%end%> >
    <!--<p class="title" data-section-title><a href="#panel2">Sent</a></p>-->
    <div class="content" data-section-content>
      <%= render "sent" %>
    </div>
  </section>
</div>

app/views/messages/new.html.erb
<h1>New messages</h1>
<div class="row">
  <div class="large-8 columns">
    <%= form_for @message do |f| %>
        <%= f.text_field :subject, :placeholder => "Subject"%>
        <%= f.select :recipient_id, User.all.collect{ |u| [u.full_name, u.id]}, {:include_blank => "Select a recipient"} %>
        <br><%= f.text_area :body, :rows => 4, style:"resize:none",:placeholder => "Message" %>
        <%= f.submit "Submit", :class => "small button success" %>
    <% end %>
  </div>
</div>

app/views/messages/show.html.erb
<div class="row">
  <div class="large-10 columns">
    <div class="large-message">
      <% if @message.recipient == current_user %>
          <%= content_tag( :span, @message.sender.full_name, :class => "name") %><br>
      <% else %>
          <%= content_tag( :span, @message.recipient.full_name, :class => "name") %>
      <% end %>
      <%= content_tag( :span, @message.subject, :class => "subject")%>
      <br/>
      <%= content_tag( :p, @message.body)%>
      <div class="clear"></div>
    </div>
  </div>
</div>
<div class="row">
  <div class="large-10 columns">
    <%= form_for Message.new do |f| %>
        <%= f.hidden_field :subject, :value => @message.subject%>
        <% recipient = @message.recipient == current_user ? @message.sender : @message.recipient %>
        <%= f.hidden_field :recipient_id, :value => recipient.id%>
        <%= f.text_area :body, :rows => 3, :placeholder => "Message" %>
        <%= f.submit "Respond", :class => "small button success right" %>
    <% end %>
  </div>
</div>