config/routes.rb
Lalala::Application.routes.draw do

  root to: "static_pages#home"

  get "signout" => "sessions#destroy"
  get "signin" => "sessions#new"
  get "signup" => "users#new", :as => "signup"


  namespace :api do
    resources :posts, except: [:new, :edit]
    resources :users, except: [:new, :edit]
    resources :messages, except: [:edit, :update]
    resources :sessions, except: [:edit, :update, :new, :show]
  end


end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <b class="navbar-brand">
        <%=link_to "Chipper", root_path %>  <span class="glyphicon glyphicon-paperclip"></span>
      </b>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
                <li ><%= link_to "Home", current_user %></li>
                <li><%= link_to "Edit",   edit_user_path(current_user) %></li>
                <li><%= link_to "Message(#{current_user.unread_message_count})", messages_path %></li>
                <li><%= link_to "Users", users_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign out", signout_path %></li>`
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Sign in", {}, remote: true, data: {toggle:'modal', target:'#Mymodal'} %></li>

        <% end %>

      </ul>




    </div><!--/.nav-collapse -->
  </div>
</nav>
<%= render 'sessions/modal' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chipper</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>

  <!--<link href="../assets/css/bootstrap.css" rel="stylesheet">-->
  <!--<link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">-->
  <link href="http://designmodo.github.io/Flat-UI/dist/css/flat-ui.min.css" rel="stylesheet">
  <style type="text/css">body{padding-top:60px;padding-bottom:40px;}
  .row{margin: 0 !important;}#footer{height:20px;background-color:#f5f5f5;margin: 20px 0 !important;}
  @media (max-width: 767px) {#footer{margin-left:-20px;margin-right:-20px;padding-left:20px;padding-right:20px;}}
  .credit{margin:20px 0;}</style>

</head>
<body style="">

<%= render 'layouts/nav' %>
<div class="container">
  <div class="row">
    <div class="">
      <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <div id="content">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

<div class="footer-copyright">
  <div class="container">
    © 2014 created by Natasha
  </div>
</div>



</body>
</html>